;;; yatex-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from yahtml.el

(register-definition-prefixes "yahtml" '("yahtml"))


;;; Generated autoloads from yatex.el

(register-definition-prefixes "yatex" '("LaTeX2e-fontstyle-alist" "NTT-jTeX" "YaTeX-" "bibtex-command" "dvi" "env-table" "fontsize-table" "latex-" "makeindex-command" "section-table" "singlecmd-table" "tex-" "tmp-" "user-" "yatex-mode"))


;;; Generated autoloads from yatex19.el

(register-definition-prefixes "yatex19" '("YaTeX-" "hilit-patterns-alist"))


;;; Generated autoloads from yatex23.el

(register-definition-prefixes "yatex23" '("YaTeX-"))


;;; Generated autoloads from yatexadd.el

(register-definition-prefixes "yatexadd" '("YaTeX"))


;;; Generated autoloads from yatexenv.el

(autoload 'YaTeX-what-column "yatexenv" "\
Show which kind of column the current position is belonging to." t)
(autoload 'YaTeX-intelligent-newline "yatexenv" "\
Insert newline and environment-specific entry.
`\\item'	for some itemizing environment,
`\\> \\> \\'	for tabbing environemnt,
`& & \\ hline'	for tabular environment.

(fn ARG)" t)
(autoload 'YaTeX-indent-line-equation "yatexenv" "\
Indent a line in equation family.")
(autoload 'YaTeX-goto-corresponding-leftright "yatexenv" "\
Go to corresponding left or ight.")
(register-definition-prefixes "yatexenv" '("YaTeX-"))


;;; Generated autoloads from yatexflt.el

(autoload 'YaTeX-filter-goto-source "yatexflt" "\
Go to corresponding text source of the graphic file

(fn FILE OTHER-WIN)")
(register-definition-prefixes "yatexflt" '("YaTeX-"))


;;; Generated autoloads from yatexgen.el

(register-definition-prefixes "yatexgen" '("YaTeX-"))


;;; Generated autoloads from yatexhie.el

(register-definition-prefixes "yatexhie" '("YaTeX-"))


;;; Generated autoloads from yatexhks.el

(register-definition-prefixes "yatexhks" '("YaTeX-browse-info"))


;;; Generated autoloads from yatexhlp.el

(autoload 'YaTeX-apropos "yatexhlp" "\


(fn KEY)" t)
(autoload 'YaTeX-help "yatexhlp" "\
Show help buffer of LaTeX/TeX commands or macros.
Optional argument MACRO, if supplied, is directly selected to keyword.
Non-nil for optional second argument REF-ONLY inhibits call enrich-help
for non-interactive use.

(fn &optional MACRO REF-ONLY)" t)
(register-definition-prefixes "yatexhlp" '("YaTeX-"))


;;; Generated autoloads from yatexinf.el

(register-definition-prefixes "yatexinf" '("yatexinfo-"))


;;; Generated autoloads from yatexlib.el

(autoload 'YaTeX-kanji-ptex-mnemonic "yatexlib" "\
Return the kanji-mnemonic of pTeX from current buffer's coding-system.")
(autoload 'YaTeX-define-key "yatexlib" "\
Define key on YaTeX-prefix-map.

(fn KEY BINDING &optional MAP)")
(autoload 'YaTeX-local-table-symbol "yatexlib" "\
Return the lisp symbol which keeps local completion table of SYMBOL.

(fn SYMBOL)")
(autoload 'YaTeX-sync-local-table "yatexlib" "\
Synchronize local variable SYMBOL.
Copy its corresponding directory dependent completion table to SYMBOL.

(fn SYMBOL)")
(autoload 'YaTeX-read-user-completion-table "yatexlib" "\
Append user completion table of LaTeX macros

(fn &optional FORCETOREAD)" t)
(autoload 'YaTeX-reload-dictionary "yatexlib" "\
Reload local dictionary.
Use this function after editing ./.yatexrc." t)
(autoload 'YaTeX-lookup-table "yatexlib" "\
Lookup WORD in completion table whose type is TYPE.
This function refers the symbol tmp-TYPE-table, user-TYPE-table, TYPE-table.
Typically, TYPE is one of 'env, 'section, 'fontsize, 'singlecmd.

(fn WORD TYPE)")
(autoload 'YaTeX-update-table "yatexlib" "\
Update completion table if the car of VALLIST is not in current tables.
Second argument DEFAULT-TABLE is the quoted symbol of default completion
table, third argument USER-TABLE is user table which will be saved in
YaTeX-user-completion-table, fourth argument LOCAL-TABLE should have the
completion which is valid during current Emacs's session.  If you
want to make LOCAL-TABLE valid longer span (but restrict in this directory)
create the file in current directory which has the same name with
YaTeX-user-completion-table.

(fn VALLIST DEFAULT-TABLE USER-TABLE LOCAL-TABLE)")
(autoload 'YaTeX-cplread-with-learning "yatexlib" "\
Completing read with learning.
Do a completing read with prompt PROM.  Completion table is what
DEFAULT-TABLE, USER-TABLE, LOCAL table are appended in reverse order.
Note that these tables are passed by the symbol.
Optional arguments PRED, REQMATH and INIT are passed to completing-read
as its arguments PREDICATE, REQUIRE-MATCH and INITIAL-INPUT respectively.
If optional 8th argument HSYM, history symbol, is passed, use it as
history list variable.

(fn PROM DEFAULT-TABLE USER-TABLE LOCAL-TABLE &optional PRED REQMATCH INIT HSYM)")
(autoload 'YaTeX-update-dictionary "yatexlib" "\


(fn FILE SYMBOL &optional TYPE)")
(autoload 'YaTeX-define-begend-key-normal "yatexlib" "\
Define short cut YaTeX-make-begin-end key.

(fn KEY ENV &optional MAP)")
(autoload 'YaTeX-define-begend-region-key "yatexlib" "\
Define short cut YaTeX-make-begin-end-region key.

(fn KEY ENV &optional MAP)")
(autoload 'YaTeX-define-begend-key "yatexlib" "\
Define short cut key for begin type completion.
Define both strokes for normal and region mode.
To customize YaTeX, user should use this function.

(fn KEY ENV &optional MAP)")
(autoload 'YaTeX-search-active-forward "yatexlib" "\
Search STRING which is not commented out by CMNTRX.
Optional arguments after BOUND, ERR, CNT are passed literally to search-forward
or search-backward.
Optional sixth argument FUNC changes search-function.

(fn STRING CMNTRX &optional BOUND ERR CNT FUNC)")
(autoload 'YaTeX-switch-to-buffer "yatexlib" "\
Switch to buffer if buffer exists, find file if not.
Optional second arg SETBUF t make use set-buffer instead of switch-to-buffer.

(fn FILE &optional SETBUF)" t)
(autoload 'YaTeX-switch-to-buffer-other-window "yatexlib" "\
Switch to buffer if buffer exists, find file if not.

(fn FILE)" t)
(autoload 'YaTeX-replace-format "yatexlib" "\
In STRING, replace first appearance of FORMAT to REPL as if
function `format' does.  FORMAT does not contain `%'

(fn STRING FORMAT REPL)")
(autoload 'YaTeX-replace-formats "yatexlib" "\


(fn STRING REPLACE-LIST)")
(autoload 'YaTeX-replace-format-args "yatexlib" "\
Translate the argument mark #1, #2, ... #n in the STRING into the
corresponding real arguments ARGS.

(fn STRING &rest ARGS)")
(autoload 'rindex "yatexlib" "\
Return the last position of STRING where character CHAR found.

(fn STRING CHAR)")
(autoload 'point-beginning-of-line "yatexlib")
(autoload 'point-end-of-line "yatexlib")
(autoload 'YaTeX-showup-buffer "yatexlib" "\
Make BUFFER show up in certain window (but current window)
that gives the maximum value by the FUNC.  FUNC should take an argument
of its window object.  Non-nil for optional third argument SELECT selects
that window.  This function never selects minibuffer window.

(fn BUFFER &optional FUNC SELECT)")
(autoload 'split-window-calculate-height "yatexlib" "\
Split current window wight specified HEIGHT.
If HEIGHT is number, make a new window that has HEIGHT lines.
If HEIGHT is string, make a new window that occupies HEIGT % of screen height.
Otherwise split window conventionally.

(fn HEIGHT)")
(autoload 'YaTeX-window-list "yatexlib")
(autoload 'substitute-all-key-definition "yatexlib" "\
Replace recursively OLDDEF with NEWDEF for any keys in KEYMAP now
defined as OLDDEF. In other words, OLDDEF is replaced with NEWDEF
where ever it appears.

(fn OLDDEF NEWDEF KEYMAP)")
(autoload 'YaTeX-match-string "yatexlib" "\
Return (buffer-substring (match-beginning n) (match-beginning m)).
Optional third argument STR gives substring from string STR.

(fn N &optional M STR)")
(autoload 'YaTeX-minibuffer-complete "yatexlib" "\
Complete in minibuffer.
  If the symbol 'delim is bound and is string, its value is assumed to be
the character class of delimiters.  Completion will be performed on
the last field separated by those delimiters.
  If the symbol 'quick is bound and is 't, when the try-completion results
in t, exit minibuffer immediately." t)
(autoload 'completing-read-with-history "yatexlib" "\
Completing read with general history: gmhist, Emacs-19.

(fn PROMPT TABLE &optional PREDICATE MUST-MATCH INITIAL HSYM)")
(autoload 'read-from-minibuffer-with-history "yatexlib" "\
Read from minibuffer with general history: gmhist, Emacs-19.

(fn PROMPT &optional INIT MAP READ HSYM)")
(autoload 'read-string-with-history "yatexlib" "\
Read string with history: gmhist(Emacs-18) and Emacs-19.

(fn PROMPT &optional INIT HSYM)")
(fset 'YaTeX-rassoc (if (and nil (fboundp 'rassoc) (subrp (symbol-function 'rassoc))) (symbol-function 'rassoc) #'(lambda (key list) (let ((l list)) (catch 'found (while l (if (equal key (cdr (car l))) (throw 'found (car l))) (setq l (cdr l))))))))
(autoload 'YaTeX-delete1 "yatexlib" "\
Delete

(fn ELT LIST)")
(fset 'YaTeX-last-key (if (fboundp 'win:last-key) 'win:last-key #'(lambda nil (if (boundp 'last-command-char) last-command-char last-command-event))))
(autoload 'YaTeX-command-to-string "yatexlib" "\


(fn CMD)")
(autoload 'YaTeX-reindent "yatexlib" "\
Remove current indentation and reindento to COL column.

(fn COL)")
(register-definition-prefixes "yatexlib" '("YaTeX-" "bcf-and-exit" "foreach-buffers" "goto-buffer-window" "latex-message-kanji-code" "tfb-and-exit"))


;;; Generated autoloads from yatexm-o.el

(register-definition-prefixes "yatexm-o" '("yatex-mode-"))


;;; Generated autoloads from yatexmth.el

(autoload 'YaTeX-toggle-math-mode "yatexmth" "\


(fn &optional ARG)" t)
(autoload 'YaTeX-goto-corresponding-paren "yatexmth" "\
Go to corresponding mathematical parentheses.")
(register-definition-prefixes "yatexmth" '("YaTeX-"))


;;; Generated autoloads from yatexpkg.el

(register-definition-prefixes "yatexpkg" '("YaTeX"))


;;; Generated autoloads from yatexprc.el

(register-definition-prefixes "yatexprc" '("YaTeX-"))


;;; Generated autoloads from yatexsec.el

(autoload 'YaTeX-read-section-in-minibuffer "yatexsec" "\


(fn PROMPT TABLE &optional DEFAULT DELIM)" t)
(autoload 'YaTeX-make-section-with-overview "yatexsec" "\
Input sectining command with previous overview." t)
(register-definition-prefixes "yatexsec" '("YaTeX-"))

;;; End of scraped data

(provide 'yatex-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; yatex-autoloads.el ends here
